<?php

declare(strict_types=1);

namespace PandawanTechnology\GeolocBundle\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260121183342 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initializes geolocation\'s tables';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE address (number VARCHAR(5) NOT NULL, repetitor VARCHAR(15) DEFAULT NULL, latitude NUMERIC(10, 8) NOT NULL, longitude NUMERIC(11, 8) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, street_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D4E6F8187CF8EB ON address (street_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D4E6F8187CF8EB96901F5451EC4692 ON address (street_id, number, repetitor)');
        $this->addSql('CREATE TABLE city (insee_code VARCHAR(5) DEFAULT NULL, post_code VARCHAR(16) NOT NULL, name VARCHAR(255) NOT NULL, country_code VARCHAR(2) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_country ON city (country_code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D5B0234F026BB7C15A3C1BC ON city (country_code, insee_code)');
        $this->addSql('CREATE TABLE street (name VARCHAR(255) NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, city_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F0EED3D88BAC62AF ON street (city_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F0EED3D88BAC62AF5E237E06 ON street (city_id, name)');
        $this->addSql('ALTER TABLE address ADD CONSTRAINT FK_D4E6F8187CF8EB FOREIGN KEY (street_id) REFERENCES street (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE street ADD CONSTRAINT FK_F0EED3D88BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE address DROP CONSTRAINT FK_D4E6F8187CF8EB');
        $this->addSql('ALTER TABLE street DROP CONSTRAINT FK_F0EED3D88BAC62AF');
        $this->addSql('DROP TABLE address');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE street');
    }
}
